<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

// Load page translations
JFactory::getLanguage()->load('page_technical_requirements', JPATH_SITE);

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

?>
<div class="item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
	<div class="page-header">
		<h1><?php echo JText::_('TECHNICAL_REQUIREMENTS_PAGE_HEADING'); ?></h1>
	</div>

	<?php if ($this->item->state == 0 || strtotime($this->item->publish_up) > strtotime(JFactory::getDate()) || ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate())) : ?>
		<div class="page-header">
			<?php if ($this->item->state == 0) : ?>
				<span class="label label-warning"><?php echo JText::_('JUNPUBLISHED'); ?></span>
			<?php endif; ?>
			<?php if (strtotime($this->item->publish_up) > strtotime(JFactory::getDate())) : ?>
				<span class="label label-warning"><?php echo JText::_('JNOTPUBLISHEDYET'); ?></span>
			<?php endif; ?>
			<?php if ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate()) : ?>
				<span class="label label-warning"><?php echo JText::_('JEXPIRED'); ?></span>
			<?php endif; ?>
		</div>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
	<?php echo $this->item->event->afterDisplayTitle; ?>

	<div class="article-info muted">
		<span class="icon-calendar" aria-hidden="true"></span> <time datetime="2021-08-17T00:00:00+00:00" itemprop="dateModified"><?php echo JText::sprintf('COM_CONTENT_LAST_UPDATED', JHtml::_('date', '2021-08-17 00:00:00', JText::_('DATE_FORMAT_LC3'))); ?></time>
	</div>

	<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
	<?php echo $this->item->event->beforeDisplayContent; ?>

	<div itemprop="articleBody">
		<div class="alert alert-info"><?php echo JText::_('TECHNICAL_REQUIREMENTS_ALERT_RECOMMENDED_VERSIONS_BASED_ON_LATEST_RELEASE'); ?></div>
		<h2><?php echo JText::_('TECHNICAL_REQUIREMENTS_HEADING_REQUIREMENTS_FOR_SUPPORTED_SOFTWARE'); ?></h2>
          
        <p>Requirements page on downloads.joomla.org is in progress for the moment we moved the technical requirements to the <a href="https://manual.joomla.org/docs/next/get-started/technical-requirements">Manual</a></p>

	<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
	<?php echo $this->item->event->afterDisplayContent; ?>
</div>
