<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

// Load page translations
JFactory::getLanguage()->load('page_faqs', JPATH_SITE);

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

// Find associations for tech requirements page, use default for layout because custom templates are set at article level and not menu item
$techRequirementsAssociations = ContentHelperAssociation::getAssociations(13, 'article', 'default');

$associatedLanguage = $this->item->language === '*' ? 'en-GB' : $this->item->language;
?>
<div class="item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
	<div class="page-header">
		<h1><?php echo JText::_('FAQS_PAGE_HEADING'); ?></h1>
	</div>

	<?php if ($this->item->state == 0 || strtotime($this->item->publish_up) > strtotime(JFactory::getDate()) || ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate())) : ?>
		<div class="page-header">
			<?php if ($this->item->state == 0) : ?>
				<span class="label label-warning"><?php echo JText::_('JUNPUBLISHED'); ?></span>
			<?php endif; ?>
			<?php if (strtotime($this->item->publish_up) > strtotime(JFactory::getDate())) : ?>
				<span class="label label-warning"><?php echo JText::_('JNOTPUBLISHEDYET'); ?></span>
			<?php endif; ?>
			<?php if ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate()) : ?>
				<span class="label label-warning"><?php echo JText::_('JEXPIRED'); ?></span>
			<?php endif; ?>
		</div>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
	<?php echo $this->item->event->afterDisplayTitle; ?>

	<div class="article-info muted">
		<span class="icon-calendar" aria-hidden="true"></span> <time datetime="2019-04-06T00:00:00+00:00" itemprop="dateModified"><?php echo JText::sprintf('COM_CONTENT_LAST_UPDATED', JHtml::_('date', '2019-04-06 00:00:00', JText::_('DATE_FORMAT_LC3'))); ?></time>
	</div>

	<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
	<?php echo $this->item->event->beforeDisplayContent; ?>

	<div itemprop="articleBody">
		<div class="row-fluid center">
			<div class="span4"><a class="btn btn-large btn-blue" href="https://docs.joomla.org" target="_blank" rel="noopener noreferrer"><?php echo JText::_('FAQS_BUTTON_JOOMLA_DOCUMENTATION'); ?></a></div>
			<div class="span4"><a class="btn btn-large btn-blue" href="<?php echo $techRequirementsAssociations[$associatedLanguage] ?? $techRequirementsAssociations['en-GB']; ?>"><?php echo JText::_('FAQS_BUTTON_TECHNICAL_REQUIREMENTS'); ?></a></div>
			<div class="span4"><a class="btn btn-large btn-blue" href="<?php echo JHtml::_('content.prepare', '{arslatest release_announcements Joomla! 3}'); ?>" target="_blank" rel="noopener noreferrer"><?php echo JText::_('FAQS_BUTTON_RELEASE_ANNOUNCEMENT'); ?></a></div>
		</div>

		<?php echo JHtml::_('bootstrap.startAccordion', 'faqs'); ?>

		<?php echo JHtml::_('bootstrap.addSlide', 'faqs', JText::_('FAQ_INSTALL_JOOMLA_LOCALLY_QUESTION'), 'faq-1'); ?>
		<?php echo JText::_('FAQ_INSTALL_JOOMLA_LOCALLY_ANSWER'); ?>
		<?php echo JHtml::_('bootstrap.endSlide'); ?>

		<?php echo JHtml::_('bootstrap.endAccordion'); ?>
	</div>

	<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
	<?php echo $this->item->event->afterDisplayContent; ?>
</div>
