<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

// Load page translations
JFactory::getLanguage()->load('page_home', JPATH_SITE);

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

?>
<div class="item-page <?php echo $this->pageclass_sfx; ?>" itemscope="" itemtype="https://schema.org/Article">
<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />

	<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
	<?php echo $this->item->event->afterDisplayTitle; ?>


	<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
	<?php echo $this->item->event->beforeDisplayContent; ?>
	
	<div itemprop="articleBody">
			<h2 class="center hp">Extend your Joomla! Installation!</h2>
		<div class="row-fluid center marge">
			<div class="span6"><img src="/images/homepage/joomla-languages.png" alt="Joomla in your language">
				<h3>Joomla! in your language</h3>
				<p>Over 70 accredited Joomla! language packages on this site!<br>Incorporate the languages you need.</p>
					<a class="btn btn-primary" title="Language packages for Joomla!" href="https://community.joomla.org/translations.html" target="_blank" rel="noopener noreferrer">
					Download Language Packages</a>
			</div>

			<div class="span6"><img src="/images/homepage/joomla-extensions.png" alt="Joomla Extensions">
			<h3>Over 8,000 Joomla! Extensions</h3>
				<p>Empower your website!<br>The JED presents thousand of ways to enhance your Joomla! site.</p>
				<a class="btn btn-primary" title="Joomla! Extensions Directory" href="https://extensions.joomla.org" target="_blank" rel="noopener noreferrer">
				Joomla! Extensions Directory</a>
			</div>
		</div>

			<h2 class="center hp">Try Joomla! 3, now!</h2>
		<div class="row-fluid center marge try">
			<div class="span6">
				<a class="btn btn-blue" title="Joomla 3" href="https://www.joomla.org/3" target="_blank" rel="noopener noreferrer">
				<span class="title">Joomla! 3</span><br>Discover the lastest features on joomla.org/3</a>
			</div>
			<div class="span6"><a class="btn btn-blue" title="Free website on launch.joomla.org" href="https://launch.joomla.org" target="_blank" rel="noopener noreferrer">
				<span class="title">launch.joomla.org</span><br>A completely free website on launch.joomla.org</a>
			</div>
		</div>


			<h2 class="hp center">Find Support!</h2>
		<div class="row-fluid center support">
			<div class="span4"><img src="/images/homepage/joomla-forum.png" alt="Joomla Forum">
				<h3>Official Forum</h3>
				<p>Need help? <br>Ask your support question on the Joomla! Forum.</p>
				<a class="btn" title="Joomla Forums" href="http://forum.joomla.org" target="_blank" rel="noopener noreferrer">Find help on the Forum</a>
			</div>
			<div class="span4"><img src="/images/homepage/joomla-documentation.png" alt="Joomla Documentation">
				<h3>Official Documentation</h3>
				<p>An online manual for users, developers or anyone interested in learning more about Joomla.</p>
				<a class="btn" title="Joomla Documentation" href="https://docs.joomla.org/S:MyLanguage/Main_Page" target="_blank" rel="noopener noreferrer">Browse our Documentation</a>
			</div>
			<div class="span4"><img src="/images/homepage/joomla-issue-tracker.png" alt="Joomla Issue Tracker">
				<h3>Issue Tracker</h3>
				<p>Test patches, find and fix bugs<br> and help clarify issue report.</p>
				<a class="btn" title="Joomla Issue Tracker" href="https://issues.joomla.org" target="_blank" rel="noopener noreferrer">Issue Tracker</a>
			</div>
		</div>
		<div class="row-fluid center marge support">
			<div class="span4"><img src="/images/homepage/joomla-migration.png" alt="Joomla Migration">
				<h3>Why and how migrate?</h3>
				<p>Resources are available to help with your migration<br> on our Official Documentation</p>
				<a class="btn" title="Why and How migrate your Joomla Website" href="https://docs.joomla.org/S:MyLanguage/Why_Migrate" target="_blank" rel="noopener noreferrer">Start now your migration</a>
			</div>
			<div class="span4"><img src="/images/homepage/joomla-25-upgrade.png" alt="Joomla 2.5 to 3">
				<h3>Migrate from 2.5 to 3.x</h3>
				<p>Plan your mini-migration<br>See the <a title="Joomla 2.5 to 3.x Step by Step Migration" href="https://docs.joomla.org/S:MyLanguage/Joomla_2.5_to_3.x_Step_by_Step_Migration" target="_blank" rel="noopener noreferrer">step by step tutorial</a></p>
				<a class="btn" title="Download Joomla 2.5" href="/cms/joomla25/2-5-28">Download 2.5.28</a>
			</div>
			<div class="span4"><img src="/images/homepage/joomla-15-upgrade.png" alt="Joomla 1.5 to 3">
				<h3>Migrate from 1.5 to 3.x</h3>
				<p>Plan your major migration<br>See the <a title="Joomla 1.5 to 3.x Step by Step Migration" href="https://docs.joomla.org/S:MyLanguage/Joomla_1.5_to_3.x_Step_by_Step_Migration" target="_blank" rel="noopener noreferrer">step by step tutorial</a></p>
				<a class="btn" title="Download Joomla 1.5" href="/cms/joomla15/1-5-26">Download 1.5.26</a></div>
			</div>
		</div>
	</div>

	<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
	<?php echo $this->item->event->afterDisplayContent; ?>

</div>
